/**
 * @file simulator/src/packets/Packet.ts
 *
 * Packet domain model for the simulation engine.
 *
 * DESIGN NOTES:
 *   - Device-level addressing: packets move between devices, not interfaces
 *   - Focus: "Can a packet move from Device A → Device B through the topology?"
 *   - Interface-level addressing can be added later via metadata or future phases
 *   - Packet identity is stable: one packet ID moves through the network
 *   - Packet state mutation is CENTRALISED through PacketStateMachine.transitionPacket().
 *     Never assign packet.state directly outside the state machine.
 *
 * LIFECYCLE (Prompt 8 formalisation):
 *
 *   CREATED
 *      │
 *      ▼
 *   QUEUED ────────────────────► DROPPED
 *      │
 *      ▼
 *   FORWARDED ─────────────────► DROPPED
 *      │   │
 *      │   └──── FORWARDED (multi-hop loop)
 *      ▼
 *   DELIVERED
 *
 *   DELIVERED and DROPPED are TERMINAL.
 */

import type { DeviceId, PacketId } from '../types/ids.js';
import type { PacketState, PacketLifecycleTransition } from './PacketStateMachine.js';

// ─── Packet Domain Model ──────────────────────────────────────────────────────

/**
 * A network packet in the simulation.
 *
 * Device-level addressing: source/destination are devices, not interfaces.
 * This keeps the model focused on device-to-device movement through the topology.
 *
 * IMMUTABLE FIELDS (never change after creation):
 *   - id, sourceDeviceId, destinationDeviceId, sourceIp, destinationIp,
 *     payload, createdAt, metadata (contents of metadata may be mutated by
 *     owners, but the metadata reference itself stays).
 *
 * CONTROLLED-MUTATION FIELDS (only via PacketEngine → transitionPacket()):
 *   - state                 (controlled by PacketStateMachine)
 *   - currentLocation       (updated on forward via PacketEngine)
 *   - history               (updated on forward via PacketEngine)
 *   - lifecycleHistory      (updated on every state transition)
 */
export interface Packet {
  /** Stable packet identifier - generated by IdFactory */
  readonly id: PacketId;

  /** Source device (where the packet originated). IMMUTABLE. */
  readonly sourceDeviceId: DeviceId;

  /** Destination device (where the packet should be delivered). IMMUTABLE. */
  readonly destinationDeviceId: DeviceId;

  /** Source IPv4 address (for routing use). IMMUTABLE. */
  readonly sourceIp: string;

  /** Destination IPv4 address (for routing use). IMMUTABLE. */
  readonly destinationIp: string;

  /** Packet payload (string for educational simulator). IMMUTABLE. */
  readonly payload: string;

  /**
   * Current device location.
   * MUTABLE but only through PacketEngine.forwardPacket() which validates
   * the graph topology before moving.
   */
  currentLocation: DeviceId;

  /**
   * Packet lifecycle state.
   * MUTABLE but ONLY through PacketStateMachine.transitionPacket().
   * Direct assignment packet.state = X is FORBIDDEN outside the SM.
   */
  state: PacketState;

  /**
   * Immutable history of visited devices (in traversal order).
   * Appended by PacketEngine on each forward hop.
   */
  readonly history: DeviceId[];

  /**
   * Immutable audit trail of every state transition, in order.
   * Appended ONLY by PacketStateMachine.transitionPacket().
   *
   * Length 0 immediately after PacketFactory.create() (CREATED is implicit
   * as initial state; the first transition entry is CREATED → QUEUED etc.).
   */
  readonly lifecycleHistory: PacketLifecycleTransition[];

  /** Creation timestamp (wall-clock ms, informational only). */
  readonly createdAt: number;

  /** Extensible metadata for future features (TTL, QoS, interface-level addressing, etc.) */
  readonly metadata?: Record<string, unknown>;
}

// ─── Packet Creation Options ───────────────────────────────────────────────────

/**
 * Options for creating a new packet.
 */
export interface CreatePacketOptions {
  /** Source device ID */
  readonly sourceDeviceId: DeviceId;

  /** Destination device ID */
  readonly destinationDeviceId: DeviceId;

  /** Source IPv4 address */
  readonly sourceIp: string;

  /** Destination IPv4 address */
  readonly destinationIp: string;

  /** Packet payload */
  readonly payload: string;

  /** Optional metadata for future extensibility */
  readonly metadata?: Record<string, unknown>;
}

// ─── Packet Factory ───────────────────────────────────────────────────────────

/**
 * Factory for creating Packet instances.
 * Centralises validation and initialisation logic.
 *
 * Guarantees for newly-created packets:
 *   1. state       = CREATED   (never anything else)
 *   2. currentLocation = sourceDeviceId
 *   3. history     = [sourceDeviceId]
 *   4. lifecycleHistory = []   (CREATED is implicit, no transition entry yet)
 */
export class PacketFactory {
  static create(options: CreatePacketOptions, idGenerator: () => PacketId): Packet {
    const packetId = idGenerator();
    const now = Date.now();

    const basePacket: Omit<Packet, 'metadata'> = {
      id: packetId,
      sourceDeviceId: options.sourceDeviceId,
      destinationDeviceId: options.destinationDeviceId,
      sourceIp: options.sourceIp,
      destinationIp: options.destinationIp,
      payload: options.payload,
      currentLocation: options.sourceDeviceId,
      state: 'CREATED',
      history: [options.sourceDeviceId],
      lifecycleHistory: [],
      createdAt: now,
    };

    if (options.metadata !== undefined) {
      return { ...basePacket, metadata: options.metadata };
    }

    return basePacket as Packet;
  }
}
