/**
 * @file simulator/src/packets/Packet.ts
 *
 * Packet domain model for the simulation engine.
 *
 * DESIGN NOTES:
 *   - Device-level addressing: packets move between devices, not interfaces
 *   - Focus: "Can a packet move from Device A → Device B through the topology?"
 *   - Interface-level addressing can be added later via metadata or future phases
 *   - Packet identity is stable: one packet ID moves through the network
 *
 * LIFECYCLE:
 *   CREATED → IN_TRANSIT → (DELIVERED | DROPPED)
 */

import type { DeviceId, PacketId } from '../types/ids.js';

// ─── Packet State ─────────────────────────────────────────────────────────────

/**
 * Packet lifecycle states.
 * Simple 4-state model for Prompt 7. Prompt 8 will formalize complete lifecycle.
 */
export type PacketState = 'CREATED' | 'IN_TRANSIT' | 'DELIVERED' | 'DROPPED';

// ─── Packet Domain Model ──────────────────────────────────────────────────────

/**
 * A network packet in the simulation.
 *
 * Device-level addressing: source/destination are devices, not interfaces.
 * This keeps Prompt 7 focused on device-to-device movement through the topology.
 */
export interface Packet {
  /** Stable packet identifier - generated by IdFactory */
  readonly id: PacketId;

  /** Source device (where the packet originated) */
  readonly sourceDeviceId: DeviceId;

  /** Destination device (where the packet should be delivered) */
  readonly destinationDeviceId: DeviceId;

  /** Source IPv4 address (for routing use) */
  readonly sourceIp: string;

  /** Destination IPv4 address (for routing use) */
  readonly destinationIp: string;

  /** Packet payload (string for educational simulator) */
  readonly payload: string;

  /** Current device location (mutable - tracks position during forwarding) */
  currentLocation: DeviceId;

  /** Packet lifecycle state */
  state: PacketState;

  /** Immutable history of visited devices (in traversal order) */
  readonly history: DeviceId[];

  /** Creation timestamp (wall-clock ms) */
  readonly createdAt: number;

  /** Extensible metadata for future features (TTL, QoS, interface-level addressing, etc.) */
  readonly metadata?: Record<string, unknown>;
}

// ─── Packet Creation Options ───────────────────────────────────────────────────

/**
 * Options for creating a new packet.
 */
export interface CreatePacketOptions {
  /** Source device ID */
  readonly sourceDeviceId: DeviceId;

  /** Destination device ID */
  readonly destinationDeviceId: DeviceId;

  /** Source IPv4 address */
  readonly sourceIp: string;

  /** Destination IPv4 address */
  readonly destinationIp: string;

  /** Packet payload */
  readonly payload: string;

  /** Optional metadata for future extensibility */
  readonly metadata?: Record<string, unknown>;
}

// ─── Packet Factory ───────────────────────────────────────────────────────────

/**
 * Factory for creating Packet instances.
 * Centralizes validation and initialization logic.
 */
export class PacketFactory {
  /**
   * Create a new packet with validation.
   *
   * This factory is responsible for:
   * - Generating a unique packet ID
   * - Initializing state to CREATED
   * - Setting current location to source device
   * - Initializing history with source device
   */
  static create(options: CreatePacketOptions, idGenerator: () => PacketId): Packet {
    const packetId = idGenerator();
    const now = Date.now();

    const basePacket: Omit<Packet, 'metadata'> = {
      id: packetId,
      sourceDeviceId: options.sourceDeviceId,
      destinationDeviceId: options.destinationDeviceId,
      sourceIp: options.sourceIp,
      destinationIp: options.destinationIp,
      payload: options.payload,
      currentLocation: options.sourceDeviceId,
      state: 'CREATED',
      history: [options.sourceDeviceId],
      createdAt: now,
    };

    // Handle metadata separately to satisfy exactOptionalPropertyTypes
    if (options.metadata !== undefined) {
      return { ...basePacket, metadata: options.metadata };
    }

    return basePacket as Packet;
  }
}
